language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script:
    phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
